defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: chimpance99
  socket: /tmp/mysql.sock

development:
  database: lainonrails_development
  <<: *defaults

test: &test
 database: lainonrails_test
 <<: *defaults

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: lainonrails_production
  pool: 5
  username: lainonrailsdb
  password: lainonrails99
  #socket: /tmp/mysql.sock

cucumber:
  <<: *test