require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CabeceraBannersController do

  # This should return the minimal set of attributes required to create a valid
  # CabeceraBanner. As you add validations to CabeceraBanner, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CabeceraBannersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cabecera_banners as @cabecera_banners" do
      cabecera_banner = CabeceraBanner.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cabecera_banners).should eq([cabecera_banner])
    end
  end

  describe "GET show" do
    it "assigns the requested cabecera_banner as @cabecera_banner" do
      cabecera_banner = CabeceraBanner.create! valid_attributes
      get :show, {:id => cabecera_banner.to_param}, valid_session
      assigns(:cabecera_banner).should eq(cabecera_banner)
    end
  end

  describe "GET new" do
    it "assigns a new cabecera_banner as @cabecera_banner" do
      get :new, {}, valid_session
      assigns(:cabecera_banner).should be_a_new(CabeceraBanner)
    end
  end

  describe "GET edit" do
    it "assigns the requested cabecera_banner as @cabecera_banner" do
      cabecera_banner = CabeceraBanner.create! valid_attributes
      get :edit, {:id => cabecera_banner.to_param}, valid_session
      assigns(:cabecera_banner).should eq(cabecera_banner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CabeceraBanner" do
        expect {
          post :create, {:cabecera_banner => valid_attributes}, valid_session
        }.to change(CabeceraBanner, :count).by(1)
      end

      it "assigns a newly created cabecera_banner as @cabecera_banner" do
        post :create, {:cabecera_banner => valid_attributes}, valid_session
        assigns(:cabecera_banner).should be_a(CabeceraBanner)
        assigns(:cabecera_banner).should be_persisted
      end

      it "redirects to the created cabecera_banner" do
        post :create, {:cabecera_banner => valid_attributes}, valid_session
        response.should redirect_to(CabeceraBanner.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cabecera_banner as @cabecera_banner" do
        # Trigger the behavior that occurs when invalid params are submitted
        CabeceraBanner.any_instance.stub(:save).and_return(false)
        post :create, {:cabecera_banner => {}}, valid_session
        assigns(:cabecera_banner).should be_a_new(CabeceraBanner)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CabeceraBanner.any_instance.stub(:save).and_return(false)
        post :create, {:cabecera_banner => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cabecera_banner" do
        cabecera_banner = CabeceraBanner.create! valid_attributes
        # Assuming there are no other cabecera_banners in the database, this
        # specifies that the CabeceraBanner created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CabeceraBanner.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cabecera_banner.to_param, :cabecera_banner => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cabecera_banner as @cabecera_banner" do
        cabecera_banner = CabeceraBanner.create! valid_attributes
        put :update, {:id => cabecera_banner.to_param, :cabecera_banner => valid_attributes}, valid_session
        assigns(:cabecera_banner).should eq(cabecera_banner)
      end

      it "redirects to the cabecera_banner" do
        cabecera_banner = CabeceraBanner.create! valid_attributes
        put :update, {:id => cabecera_banner.to_param, :cabecera_banner => valid_attributes}, valid_session
        response.should redirect_to(cabecera_banner)
      end
    end

    describe "with invalid params" do
      it "assigns the cabecera_banner as @cabecera_banner" do
        cabecera_banner = CabeceraBanner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CabeceraBanner.any_instance.stub(:save).and_return(false)
        put :update, {:id => cabecera_banner.to_param, :cabecera_banner => {}}, valid_session
        assigns(:cabecera_banner).should eq(cabecera_banner)
      end

      it "re-renders the 'edit' template" do
        cabecera_banner = CabeceraBanner.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CabeceraBanner.any_instance.stub(:save).and_return(false)
        put :update, {:id => cabecera_banner.to_param, :cabecera_banner => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cabecera_banner" do
      cabecera_banner = CabeceraBanner.create! valid_attributes
      expect {
        delete :destroy, {:id => cabecera_banner.to_param}, valid_session
      }.to change(CabeceraBanner, :count).by(-1)
    end

    it "redirects to the cabecera_banners list" do
      cabecera_banner = CabeceraBanner.create! valid_attributes
      delete :destroy, {:id => cabecera_banner.to_param}, valid_session
      response.should redirect_to(cabecera_banners_url)
    end
  end

end
