require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComputestsController do

  # This should return the minimal set of attributes required to create a valid
  # Computest. As you add validations to Computest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComputestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all computests as @computests" do
      computest = Computest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:computests).should eq([computest])
    end
  end

  describe "GET show" do
    it "assigns the requested computest as @computest" do
      computest = Computest.create! valid_attributes
      get :show, {:id => computest.to_param}, valid_session
      assigns(:computest).should eq(computest)
    end
  end

  describe "GET new" do
    it "assigns a new computest as @computest" do
      get :new, {}, valid_session
      assigns(:computest).should be_a_new(Computest)
    end
  end

  describe "GET edit" do
    it "assigns the requested computest as @computest" do
      computest = Computest.create! valid_attributes
      get :edit, {:id => computest.to_param}, valid_session
      assigns(:computest).should eq(computest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Computest" do
        expect {
          post :create, {:computest => valid_attributes}, valid_session
        }.to change(Computest, :count).by(1)
      end

      it "assigns a newly created computest as @computest" do
        post :create, {:computest => valid_attributes}, valid_session
        assigns(:computest).should be_a(Computest)
        assigns(:computest).should be_persisted
      end

      it "redirects to the created computest" do
        post :create, {:computest => valid_attributes}, valid_session
        response.should redirect_to(Computest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved computest as @computest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Computest.any_instance.stub(:save).and_return(false)
        post :create, {:computest => {}}, valid_session
        assigns(:computest).should be_a_new(Computest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Computest.any_instance.stub(:save).and_return(false)
        post :create, {:computest => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested computest" do
        computest = Computest.create! valid_attributes
        # Assuming there are no other computests in the database, this
        # specifies that the Computest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Computest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => computest.to_param, :computest => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested computest as @computest" do
        computest = Computest.create! valid_attributes
        put :update, {:id => computest.to_param, :computest => valid_attributes}, valid_session
        assigns(:computest).should eq(computest)
      end

      it "redirects to the computest" do
        computest = Computest.create! valid_attributes
        put :update, {:id => computest.to_param, :computest => valid_attributes}, valid_session
        response.should redirect_to(computest)
      end
    end

    describe "with invalid params" do
      it "assigns the computest as @computest" do
        computest = Computest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Computest.any_instance.stub(:save).and_return(false)
        put :update, {:id => computest.to_param, :computest => {}}, valid_session
        assigns(:computest).should eq(computest)
      end

      it "re-renders the 'edit' template" do
        computest = Computest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Computest.any_instance.stub(:save).and_return(false)
        put :update, {:id => computest.to_param, :computest => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested computest" do
      computest = Computest.create! valid_attributes
      expect {
        delete :destroy, {:id => computest.to_param}, valid_session
      }.to change(Computest, :count).by(-1)
    end

    it "redirects to the computests list" do
      computest = Computest.create! valid_attributes
      delete :destroy, {:id => computest.to_param}, valid_session
      response.should redirect_to(computests_url)
    end
  end

end
