require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfertasController do

  # This should return the minimal set of attributes required to create a valid
  # Oferta. As you add validations to Oferta, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfertasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ofertas as @ofertas" do
      oferta = Oferta.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ofertas).should eq([oferta])
    end
  end

  describe "GET show" do
    it "assigns the requested oferta as @oferta" do
      oferta = Oferta.create! valid_attributes
      get :show, {:id => oferta.to_param}, valid_session
      assigns(:oferta).should eq(oferta)
    end
  end

  describe "GET new" do
    it "assigns a new oferta as @oferta" do
      get :new, {}, valid_session
      assigns(:oferta).should be_a_new(Oferta)
    end
  end

  describe "GET edit" do
    it "assigns the requested oferta as @oferta" do
      oferta = Oferta.create! valid_attributes
      get :edit, {:id => oferta.to_param}, valid_session
      assigns(:oferta).should eq(oferta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Oferta" do
        expect {
          post :create, {:oferta => valid_attributes}, valid_session
        }.to change(Oferta, :count).by(1)
      end

      it "assigns a newly created oferta as @oferta" do
        post :create, {:oferta => valid_attributes}, valid_session
        assigns(:oferta).should be_a(Oferta)
        assigns(:oferta).should be_persisted
      end

      it "redirects to the created oferta" do
        post :create, {:oferta => valid_attributes}, valid_session
        response.should redirect_to(Oferta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved oferta as @oferta" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oferta.any_instance.stub(:save).and_return(false)
        post :create, {:oferta => {}}, valid_session
        assigns(:oferta).should be_a_new(Oferta)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oferta.any_instance.stub(:save).and_return(false)
        post :create, {:oferta => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested oferta" do
        oferta = Oferta.create! valid_attributes
        # Assuming there are no other ofertas in the database, this
        # specifies that the Oferta created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Oferta.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => oferta.to_param, :oferta => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested oferta as @oferta" do
        oferta = Oferta.create! valid_attributes
        put :update, {:id => oferta.to_param, :oferta => valid_attributes}, valid_session
        assigns(:oferta).should eq(oferta)
      end

      it "redirects to the oferta" do
        oferta = Oferta.create! valid_attributes
        put :update, {:id => oferta.to_param, :oferta => valid_attributes}, valid_session
        response.should redirect_to(oferta)
      end
    end

    describe "with invalid params" do
      it "assigns the oferta as @oferta" do
        oferta = Oferta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oferta.any_instance.stub(:save).and_return(false)
        put :update, {:id => oferta.to_param, :oferta => {}}, valid_session
        assigns(:oferta).should eq(oferta)
      end

      it "re-renders the 'edit' template" do
        oferta = Oferta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oferta.any_instance.stub(:save).and_return(false)
        put :update, {:id => oferta.to_param, :oferta => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested oferta" do
      oferta = Oferta.create! valid_attributes
      expect {
        delete :destroy, {:id => oferta.to_param}, valid_session
      }.to change(Oferta, :count).by(-1)
    end

    it "redirects to the ofertas list" do
      oferta = Oferta.create! valid_attributes
      delete :destroy, {:id => oferta.to_param}, valid_session
      response.should redirect_to(ofertas_url)
    end
  end

end
