require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecetasController do

  # This should return the minimal set of attributes required to create a valid
  # Receta. As you add validations to Receta, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecetasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recetas as @recetas" do
      receta = Receta.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recetas).should eq([receta])
    end
  end

  describe "GET show" do
    it "assigns the requested receta as @receta" do
      receta = Receta.create! valid_attributes
      get :show, {:id => receta.to_param}, valid_session
      assigns(:receta).should eq(receta)
    end
  end

  describe "GET new" do
    it "assigns a new receta as @receta" do
      get :new, {}, valid_session
      assigns(:receta).should be_a_new(Receta)
    end
  end

  describe "GET edit" do
    it "assigns the requested receta as @receta" do
      receta = Receta.create! valid_attributes
      get :edit, {:id => receta.to_param}, valid_session
      assigns(:receta).should eq(receta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Receta" do
        expect {
          post :create, {:receta => valid_attributes}, valid_session
        }.to change(Receta, :count).by(1)
      end

      it "assigns a newly created receta as @receta" do
        post :create, {:receta => valid_attributes}, valid_session
        assigns(:receta).should be_a(Receta)
        assigns(:receta).should be_persisted
      end

      it "redirects to the created receta" do
        post :create, {:receta => valid_attributes}, valid_session
        response.should redirect_to(Receta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved receta as @receta" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receta.any_instance.stub(:save).and_return(false)
        post :create, {:receta => {}}, valid_session
        assigns(:receta).should be_a_new(Receta)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receta.any_instance.stub(:save).and_return(false)
        post :create, {:receta => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested receta" do
        receta = Receta.create! valid_attributes
        # Assuming there are no other recetas in the database, this
        # specifies that the Receta created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Receta.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => receta.to_param, :receta => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested receta as @receta" do
        receta = Receta.create! valid_attributes
        put :update, {:id => receta.to_param, :receta => valid_attributes}, valid_session
        assigns(:receta).should eq(receta)
      end

      it "redirects to the receta" do
        receta = Receta.create! valid_attributes
        put :update, {:id => receta.to_param, :receta => valid_attributes}, valid_session
        response.should redirect_to(receta)
      end
    end

    describe "with invalid params" do
      it "assigns the receta as @receta" do
        receta = Receta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receta.any_instance.stub(:save).and_return(false)
        put :update, {:id => receta.to_param, :receta => {}}, valid_session
        assigns(:receta).should eq(receta)
      end

      it "re-renders the 'edit' template" do
        receta = Receta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receta.any_instance.stub(:save).and_return(false)
        put :update, {:id => receta.to_param, :receta => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested receta" do
      receta = Receta.create! valid_attributes
      expect {
        delete :destroy, {:id => receta.to_param}, valid_session
      }.to change(Receta, :count).by(-1)
    end

    it "redirects to the recetas list" do
      receta = Receta.create! valid_attributes
      delete :destroy, {:id => receta.to_param}, valid_session
      response.should redirect_to(recetas_url)
    end
  end

end
